version: '3.8'
services:
  web:
    image: nginx:1.8
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    ports:
      - "8008:80"
    depends_on:
      - php
      - db

  php:
    image: php:8.0-fpm
    volumes:
      - ./www:/var/www/html
    healthcheck:
      test: ["CMD", "php-fpm", "-v"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: my-network
